all:
	mpic++ -o tema4 tema4.cpp routing.cpp -Wall

run_7:
	mpirun -np 7 tema4 topologie_7 mesaje

run_12:
	mpirun -np 12 tema4 topologie_12 mesaje

run_13: 
	mpirun -np 13 tema4 topologie_13 mesaje

clean:
	rm -f tema4
	rm -f route*
